- app/models/employment/frontend/EmploymentData.scala
- app/models/employment/shared/Pay.scala
- it/api/GetIncomeSourcesFromSessionITest.scala
- it/connectors/GetEmploymentConnectorISpec.scala
- it/repositories/IncomeTaxUserDataRepositoryISpec.scala
- test/utils/TestUtils.scala
Updated the Pay model in EmploymentData to align with the latest DES Spec (2.0.0)
[SASS-896](https://jira.tools.tax.service.gov.uk/browse/SASS-896)
> [SASS-896] Update Pay model to align with the latest DES Spec

- app/models/employment/frontend/EmploymentData.scala
- app/models/employment/shared/Deductions.scala
- app/models/employment/shared/StudentLoans.scala
- it/api/GetIncomeSourcesFromSessionITest.scala
- it/connectors/GetEmploymentConnectorISpec.scala
- it/repositories/IncomeTaxUserDataRepositoryISpec.scala
- project/AppDependencies.scala
- project/plugins.sbt
- test/models/IncomeSourcesResponseModelSpec.scala
- test/utils/TestUtils.scala
https://jira.tools.tax.service.gov.uk/browse/SASS-1067
> SASS-1067 - Added additional data items in employment models

- it/repositories/IncomeTaxUserDataRepositoryISpec.scala
- project/AppDependencies.scala
Fix the income tax submission build failing in Jenkins and update the dependencies to their latest versions.
[SASS-1637](https://jira.tools.tax.service.gov.uk/browse/SASS-1637)
> SASS-1637: Fix income tax submission build failing

- app/config/AppConfig.scala
- it/api/GetIncomeSourcesFromSessionITest.scala
- it/connectors/GetDividendsConnectorISpec.scala
- it/connectors/GetEmploymentConnectorISpec.scala
- it/connectors/GetGiftAidConnectorISpec.scala
- it/connectors/GetInterestConnectorISpec.scala
- it/repositories/IncomeTaxUserDataRepositoryISpec.scala
- test/utils/MockAppConfig.scala
- test/utils/SecureGCMCipherSpec.scala
- test/utils/TestUtils.scala
Removal of Injection in Unit tests
[SASS-739](https://jira.tools.tax.service.gov.uk/browse/SASS-739)
> SASS-1610 : Removed Injection from Unit tests

- app/controllers/IncomeSourcesController.scala
- app/models/RefreshIncomeSource.scala
- app/services/GetIncomeSourcesService.scala
- app/services/IncomeTaxUserDataService.scala
- app/services/RefreshCacheService.scala
- conf/app.routes
- it/api/RefreshIncomeSourceITest.scala
- project/AppDependencies.scala
- project/plugins.sbt
- test/controllers/IncomeSourcesControllerSpec.scala
- test/services/RefreshCacheServiceSpec.scala
- test/utils/TestUtils.scala
https://jira.tools.tax.service.gov.uk/browse/SASS-1306
To be merged alongside https://github.com/hmrc/income-tax-employment-frontend/pull/245
> SASS-1839 Added refresh cache API

- app/models/employment/AllEmploymentData.scala
- app/models/employment/EmploymentFinancialData.scala
- app/models/employment/EmploymentSource.scala
- app/services/EncryptionService.scala
- build.sbt
- project/AppDependencies.scala
- project/build.properties
- test/builders/models/employment/AllEmploymentDataBuilder.scala
- test/builders/models/employment/EmploymentSourceBuilder.scala
- test/models/IncomeSourcesSpec.scala
> SASS-2396 Updated model and encryption methods

- app/models/employment/AllEmploymentData.scala
- app/models/employment/EmploymentData.scala
- app/models/employment/EmploymentFinancialData.scala
- app/models/employment/EmploymentSource.scala
- app/models/employment/HmrcEmploymentSource.scala
- app/services/EncryptionService.scala
- app/services/GetIncomeSourcesService.scala
- project/AppDependencies.scala
- test/builders/models/employment/EmploymentFinancialDataBuilder.scala
- test/builders/models/employment/HmrcEmploymentSourceBuilder.scala
- test/models/employment/AllEmploymentDataSpec.scala
- test/models/employment/EmploymentDataSpec.scala
- test/models/employment/EmploymentFinancialDataSpec.scala
- test/models/employment/EmploymentSourceSpec.scala
- test/models/employment/HmrcEmploymentSourceSpec.scala
- test/services/GetIncomeSourcesServiceSpec.scala
[SASS-2763](https://jira.tools.tax.service.gov.uk/browse/SASS-2763)
> SASS-2763 - Align to latest spec for API #1645.

- app/connectors/parsers/SubmittedPensionsParser.scala
- app/models/employment/AllEmploymentData.scala
- app/models/employment/HmrcEmploymentSource.scala
- app/models/pensions/Pensions.scala
- app/models/pensions/employmentPensions/EmploymentPensions.scala
- app/services/EncryptionService.scala
- app/services/GetIncomeSourcesService.scala
- it/connectors/IncomeTaxPensionsConnectorISpec.scala
- test/builders/models/IncomeSourcesBuilder.scala
- test/builders/models/employment/AllEmploymentDataBuilder.scala
- test/builders/models/employment/EmploymentDataBuilder.scala
- test/builders/models/employment/EmploymentFinancialDataBuilder.scala
- test/builders/models/employment/HmrcEmploymentSourceBuilder.scala
- test/builders/models/pensions/PensionsBuilder.scala
- test/builders/models/pensions/employmentPensions/EmploymentPensionsBuilder.scala
- test/services/GetIncomeSourcesServiceSpec.scala
Added employments pensions items to pensions model
[SASS-2706](https://jira.tools.tax.service.gov.uk/browse/SASS-2706)
> [SASS-2706] - added employmentPensions to pensionsModel

- README.md
Updating the README.md file for income-tax-submission
[SASS-2935](https://jira.tools.tax.service.gov.uk/browse/SASS-2935)
> SASS-2970 Updated README.md

- app/controllers/ExcludeJourneyController.scala
- app/models/ExcludeJourneyModel.scala
- app/models/GetExclusionsDataModel.scala
- app/models/mongo/ExclusionUserDataModel.scala
- app/models/mongo/ExclusionUserDataTemplate.scala
- app/repositories/ExclusionRepositoryIndexes.scala
- app/repositories/ExclusionUserDataRepository.scala
- app/repositories/UserDataRepository.scala
- app/services/ExcludeJourneyService.scala
- app/services/ExclusionEncryptionService.scala
- app/utils/PagerDutyHelper.scala
- app/utils/ShaHashHelper.scala
- conf/app.routes
- it/repositories/UserDataRepositoryISpec.scala
- test/controllers/ExcludeJourneyControllerSpec.scala
- test/models/GetExclusionsDataModelSpec.scala
- test/services/ExcludeJourneyServiceSpec.scala
Added in the exclusion logic that was present in itsf
> [DM] [SASS-2833] Added in exclusion logic

- it/api/GetIncomeSourcesFromSessionITest.scala
- it/api/GetIncomeSourcesITest.scala
- it/api/RefreshIncomeSourceITest.scala
- project/AppDependencies.scala
[SASS-3123](https://jira.tools.tax.service.gov.uk/browse/SASS-3123)
> SASS-3123 - Update bootstrap-BE/FE-play-28 dependencies.

- app/controllers/ExcludeJourneyController.scala
- project/AppDependencies.scala
- test/controllers/ExcludeJourneyControllerSpec.scala
[SASS-3177](https://jira.tools.tax.service.gov.uk/browse/SASS-3177)
> add pensions to excludeJourneyList

- app/connectors/parsers/SubmittedPensionsParser.scala
- app/models/pensions/Pensions.scala
- app/models/pensions/income/PensionIncome.scala
- app/services/EncryptionService.scala
- it/connectors/IncomeTaxPensionsConnectorISpec.scala
- project/AppDependencies.scala
- test/builders/models/pensions/PensionsBuilder.scala
- test/builders/models/pensions/income/PensionIncome.scala
- test/models/PensionsSpec.scala
Reverts hmrc/income-tax-submission#49
Necessary work has taken place to breaks that were previously caused by this PR.
> Revert "Revert "Sass 3250""

- app/models/statebenefits/AllStateBenefitsData.scala
- test/builders/models/statebenefits/AllStateBenefitsDataBuilder.scala
> I[Fix] Api model change.

- app/connectors/IncomeTaxInterestSavingsConnector.scala
- app/connectors/parsers/SubmittedInterestSavingsParser.scala
- app/controllers/ExcludeJourneyController.scala
- app/controllers/IncomeSourcesController.scala
- app/models/ForeignInterestModel.scala
- app/models/IncomeSources.scala
- app/models/SavingsIncomeDataModel.scala
- app/models/SecuritiesModel.scala
- app/models/mongo/UserData.scala
- app/services/EncryptionService.scala
- app/services/GetIncomeSourcesService.scala
- app/services/IncomeTaxUserDataService.scala
- app/services/RefreshCacheService.scala
- it/api/GetIncomeSourcesITest.scala
- it/connectors/IncomeTaxInterestSavingsConnectorISpec.scala
- it/services/EncryptionServiceISpec.scala
- test/builders/models/IncomeSourcesBuilder.scala
- test/builders/models/SavingsIncomeBuilder.scala
- test/builders/models/mongo/UserDataBuilder.scala
- test/services/GetIncomeSourcesServiceSpec.scala
[SASS-3345](https://jira.tools.tax.service.gov.uk/browse/SASS-3345)
> SASS-3360 add savings interest

- app/controllers/IncomeSourcesController.scala
- app/models/IncomeSources.scala
- app/models/mongo/UserData.scala
- app/services/GetIncomeSourcesService.scala
- app/services/RefreshCacheService.scala
- conf/application.conf
- it/api/GetIncomeSourcesITest.scala
- project/AppDependencies.scala
- project/plugins.sbt
- test/builders/models/IncomeSourcesBuilder.scala
- test/controllers/IncomeSourcesControllerSpec.scala
- test/models/IncomeSourcesSpec.scala
- test/services/GetIncomeSourcesServiceSpec.scala
- test/services/IncomeTaxUserDataServiceSpec.scala
- test/services/RefreshCacheServiceSpec.scala
Allow overview to display when single non fatal error occurs
[SASS-3963](https://jira.tools.tax.service.gov.uk/browse/SASS-3963)
> SASS-3963: Allow overview to display when single non fatal error occurs

- app/services/GetIncomeSourcesService.scala
- test/services/GetIncomeSourcesServiceSpec.scala
> return None for empty pensions

- app/models/pensions/charges/PensionSavingsTaxCharges.scala
- app/models/pensions/charges/PensionSchemeUnauthorisedPayments.scala
- app/models/pensions/income/PensionIncome.scala
- app/services/EncryptionService.scala
- test/builders/models/pensions/charges/PensionSavingsTaxChargesBuilder.scala
- test/builders/models/pensions/charges/PensionSchemeUnauthorisedPaymentsBuilder.scala
- test/builders/models/pensions/income/PensionIncome.scala
- test/controllers/ExcludeJourneyControllerSpec.scala
[SASS-4685](https://jira.tools.tax.service.gov.uk/browse/SASS-4685)
> SASS-4685 - Updated Pension Models correctly to reflect API and fix bug

- app/models/pensions/charges/PensionSavingsTaxCharges.scala
- app/services/EncryptionService.scala
- test/builders/models/pensions/charges/PensionSavingsTaxChargesBuilder.scala
Updated PensionSavingsTaxCharges model
> SASS-3445: Implement Saving For 'Check Annual Allowances' CYA Page

- app/models/employment/EmploymentData.scala
- app/services/EncryptionService.scala
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
- test/builders/models/employment/EmploymentDataBuilder.scala
Adding offPayrollWorker field.
[SASS-5554](https://jira.tools.tax.service.gov.uk/browse/SASS-5554)
> SASS-5554: Get Employment Detail View

- app/connectors/parsers/SubmittedGainsParser.scala
- app/models/gains/InsurancePoliciesModel.scala
- app/services/EncryptionService.scala
- app/services/GetIncomeSourcesService.scala
- it/connectors/IncomeTaxGainsConnectorISpec.scala
- test/builders/models/gains/GainsBuilder.scala
- test/models/InsurancePoliciesModelSpec.scala
- test/services/GetIncomeSourcesServiceSpec.scala
Update insurance policies model, add logging
> SASS-6664: Update insurance policies model, add logging

- app/connectors/parsers/APIParser.scala
- app/services/GetIncomeSourcesService.scala
- conf/application-json-logger.xml
- conf/application.conf
- conf/logback.xml
- test/connectors/parsers/APIParserSpec.scala
Add logging configuration for displaying in kibana
> SASS-7179: Fix logging

- app/models/tasklist/TaskTitle.scala
- test/models/tasklist/TaskTitleSpec.scala
> SASS-8663: Add an additional Option to the Charitable Donations Page

- app/connectors/AdditionalInfoTaskListDataConnector.scala
- app/connectors/DividendsTaskListDataConnector.scala
- app/connectors/PensionTaskListDataConnector.scala
- app/connectors/parsers/TaskListAPIParser.scala
- app/connectors/parsers/TaskListAdditionalInfoDataParser.scala
- app/connectors/parsers/TaskListDividendDataParser.scala
- app/connectors/parsers/TaskListPensionDataParser.scala
- app/connectors/parsers/TaskListTailoringDataParser.scala
- app/controllers/TaskListDataController.scala
- app/services/RefreshCacheService.scala
- app/services/TaskListDataService.scala
- it/test/connectors/AdditionalInfoTaskListDataConnectorISpec.scala
- it/test/connectors/DividendsTaskListDataConnectorISpec.scala
- it/test/connectors/PensionTaskListDataConnectorISpec.scala
- project/AppDependencies.scala
- test/controllers/TaskListDataControllerSpec.scala
- test/services/TaskListDataServiceSpec.scala
Integrate Downstream API to merge Tailoring Data and generate Task list items
[SASS-9324](https://jira.tools.tax.service.gov.uk/browse/SASS-9324)
> Sass 9324 - Merge data from downstream to generate Common tasklist

- app/connectors/CharitableDonationsTaskListDataConnector.scala
- app/connectors/parsers/APIParser.scala
- app/connectors/parsers/TaskListCharitableDonationsDataParser.scala
- app/controllers/TaskListDataController.scala
- app/services/TaskListDataService.scala
- it/test/connectors/CharitableDonationsTaskListDataConnectorISpec.scala
- it/test/connectors/PensionTaskListDataConnectorISpec.scala
- test/controllers/TaskListDataControllerSpec.scala
- test/services/TaskListDataServiceSpec.scala
Integrate charitable donations task list endpoint.
> SASS-9530: Integrate charitable donations task list endpoint

- app/connectors/InterestTaskListDataConnector.scala
- app/connectors/parsers/TaskListInterestDataParser.scala
- app/services/TaskListDataService.scala
- it/test/connectors/InterestTaskListDataConnectorISpec.scala
- test/services/TaskListDataServiceSpec.scala
> SASS-9593: Integrated Interest Task List endpoint

- app/connectors/CISTaskListDataConnector.scala
- app/connectors/StateBenefitsTaskListDataConnector.scala
- app/connectors/parsers/TaskListAPIParser.scala
- app/connectors/parsers/TaskListCISDataParser.scala
- app/connectors/parsers/TaskListStateBenefitsDataParser.scala
- app/services/TaskListDataService.scala
- it/test/connectors/CISTaskListDataConnectorISpec.scala
- it/test/connectors/StateBenefitsTaskListDataConnectorISpec.scala
- test/services/TaskListDataServiceSpec.scala
This covers Hyperlink task for CIS,ESA,JSA and Pension (integration)
> SASS-9685 - This covers Hyperlink task for CIS,ESA,JSA and Pension.

- app/connectors/EmploymentTaskListDataConnector.scala
- app/connectors/parsers/TaskListEmploymentDataParser.scala
- app/services/TaskListDataService.scala
- it/test/connectors/EmploymentTaskListDataConnectorISpec.scala
- test/services/TaskListDataServiceSpec.scala
> SASS-10003: Integrating employment tasklist endpoint

- app/connectors/parsers/TaskListAPIParser.scala
- app/controllers/TaskListDataController.scala
- test/controllers/TaskListDataControllerSpec.scala
Update cache for certain income sources
> SASS-10088: Update cache for certain income sources

- app/services/TaskListDataService.scala
- test/services/TaskListDataServiceSpec.scala
Main ticket: [SASS-10057](https://jira.tools.tax.service.gov.uk/browse/SASS-10057)
> SASS-10064: Updating the Tailoring task list data is not found response

- app/controllers/TaskListDataController.scala
- app/services/TaskListDataService.scala
- test/services/TaskListDataServiceSpec.scala
> Change status to not started in case of non pre-pop journeys.

- app/controllers/TaskListDataController.scala
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
Current overview page would update the cache so entering the journey previous data would be displayed.  Since we made the CTL the cache would not always be up to date.  This PR fixes that issue.
> SASS-10109: Update cache on CTL

- app/controllers/TaskListDataController.scala
Update logic for calling cache
> SASS-10109: Update logic for calling cache

- app/connectors/parsers/TaskListAPIParser.scala
- app/services/TaskListDataService.scala
> Fix to handle downstream error

- app/services/TaskListDataService.scala
> generalised error handling

- app/common/EnrolmentCommon.scala
- app/config/AppConfig.scala
- app/controllers/predicates/AuthorisedAction.scala
- app/models/User.scala
- check.sh
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
- test/common/EnrolmentCommonSpec.scala
- test/controllers/ExcludeJourneyControllerSpec.scala
- test/controllers/predicates/AuthorisedActionSpec.scala
- test/utils/MockAppConfig.scala
- test/utils/TestUtils.scala
> SASS-11006: Enabling Multi- Agent for Income-tax-submission - Backend

- app/config/AppConfig.scala
- build.sbt
- conf/application.conf
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- test/utils/MockAppConfig.scala
> [SASS-11541]Create feature switch to enable call to self employment "Tasks" API

- app/services/TaskListDataService.scala
- it/test/connectors/SelfEmploymentTaskListDataConnectorISpec.scala
- test/services/TaskListDataServiceSpec.scala
> SASS-11542

- app/config/AppConfig.scala
- app/connectors/PropertyTaskListDataConnector.scala
- app/connectors/parsers/TaskListPropertyDataParser.scala
- app/models/tasklist/SectionTitle.scala
- app/models/tasklist/TaskTitle.scala
- conf/application.conf
- it/test/connectors/PropertyTaskListDataConnectorISpec.scala
- it/test/utils/ConnectorIntegrationTest.scala
- test/models/tasklist/SectionTitleSpec.scala
- test/models/tasklist/TaskTitleSpec.scala
- test/utils/MockAppConfig.scala
App-Config-Base:
- https://github.com/hmrc/app-config-base/pull/12005
> [SASS-11578] Add PropertyTaskListConnector
